#include "TMU_Pb.h"
#include "APP.h"

/*
Str_TMU_Cfg LED_1 = {LED1,1000,TMU_ONE_SHOT,FUNCTION_READY};
Str_TMU_Cfg LED_2 = {LED2,1000,TMU_PERIODIC,FUNCTION_READY};
Str_TMU_Cfg LED_3 = {LED3,3000,TMU_PERIODIC,FUNCTION_READY};
Str_TMU_Cfg LED_4 = {LED4,4000,TMU_PERIODIC,FUNCTION_READY};
*/