#include "TMU_Pb.h"
#include "APP.h"

/*
Str_TMU_Cfg LED_1 = {LED1,100,TMU_ONE_SHOT,FUNCTION_READY};
Str_TMU_Cfg LED_2 = {LED2,200,TMU_PERIODIC,FUNCTION_READY};
Str_TMU_Cfg LED_3 = {LED3,500,TMU_PERIODIC,FUNCTION_READY};
Str_TMU_Cfg LED_4 = {LED4,800,TMU_PERIODIC,FUNCTION_READY};
*/